### ISSUE TITLE
Quick code review

### ISSUE THREAD

**Issue by mdeff** [illorens/weather_prediction#4]
I did a quick pass over your code. Looks good and well organized! Some comments below.

* Class names should use CamelCase, e.g., `Weather_Dataset` should be `WeatherDataset`. Python coding style is dictated by [PEP8](https://www.python.org/dev/peps/pep-0008/).
* Names should be more explicit. It's hard to tell what is the difference between `Weather_Dataset`, `Dataset_WeatherBench_1D`, and `Dataset_WeatherBench_2D` from their name. Be more explicit.
* Related: write a short docstring explaining what it is. Don't overdo it, no need for an exhaustive description of all the parameters. Your future self will thank you.
* Reasonably avoid redundancy. The three classes mentioned above are very similar. Could common functionality be factored out? That helps to avoid bugs in the future. Again don't overdo it, it's better to copy-paste a bit than to introduce a lot of complexity. Everything is a trade-off.
* Prefer "Hungarian" / reverse naming. For example, `PeriodicConv2D` is better named `Conv2DPeriodic`. It's reverse because in English you'd call it a periodic 2D convolution. The reason to name in reverse order is that when you'll use it, you will first think of a Conv, then 2D, then Periodic. You're auto-completer will suggest completion in that order. Note that I too did this mistake with `ChebConv` (you can fix it). Sometimes it's not clear what's the reverse name (e.g., `HealpixAvgPool` or `PoolAvgHealpix`, it depends how you look at the hierarchy), no big deal.
* Private functions (those that won't be used outside of a module or class, like `equiangular_calculator`) should start with an underscore.
* `import modules.layers as layers` => `from modules import layers`
* Some things seem to be implemented in both notebooks and modules (like `Dataset_2D`, `PeriodicConv2D_torch`, etc. in `pytorch_weatherbench.ipynb`, many in `data_processing.ipynb`). My suggestion: develop in the notebook, once ready move to module and delete from notebook.
* As a general rule-of-thumb, notebooks should be used to tell stories, while modules contain the bulk of the code. An alternative to notebooks is to use scripts (saving images instead of displaying them).
* Have a `data` folder. You can add small data in the git repo (like `weatherbench_training.txt`), and put instructions in the README in how to get larger data in there.
* Use relative paths. For example, `"../data/predictions/..."` instead of `"/mnt/scratch/students/illorens/data/predictions/..."`.
* Data pre-processing (e.g., from xarray to numpy, standardization, etc.) should go in a script. Then you can write in the README: 1 download data with xxx, 2 preprocess with xxx, 3 run model with xxx, 4 visualize results with xxx.
* Fix #3.

Thanks for your great work!

**Comment by illorens** [comment]
Thanks a lot for your useful feedback!
